### ISSUE TITLE
Eldrazi Scions are named incorrectly

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Magic-Token#10]
Unlike all other tokens with multiple versions, Eldrazi Scion is differentiated by adding `(n)` to the end, instead of adding whitespace.

I am on a phone, otherwise I'd PR a fix

**Comment by Psithief** [comment]
Won't fix. They are all exactly the same token, and normally only get one entry in the file. If you do not want to use them, you don't have to.

**Comment by skwerlman** [comment]
Fair enough
