### ISSUE TITLE
Summoners Bane

### ISSUE THREAD

**Issue by DoomStrider** [Cockatrice/Magic-Token#105]
Summoners bane tries to make a 1/1 illusion instead of the proper 2/2 illusion. 

(Forgot to give credit, noticed by thrall from the discord.)

**Comment by tooomm** [comment]
Nice catch. The image file got mixed up.

Thanks for coming here to report that issue and carry it over from Discord!! 👍 

I applied a fix. It will be available via the Oracle updater in Cockatrice once others confirm it and this issue gets closed (probably within the next few days).
This is a temporary working file in case you want to test it: https://github.com/Cockatrice/Magic-Token/blob/tooomm-patch-1/tokens.xml

**Comment by Psithief** [comment]
Only _almost_ perfect. 🐀s
