### ISSUE TITLE
Modern Horizons 2 Beast Token

### ISSUE THREAD

**Issue by Giovanni-Boss** [Cockatrice/Magic-Token#109]
Hello again. This time the issue is basically the same as last time. The MH2 Beast token is listed together with the 3/3 Beast tokens, instead of the 4/4 beast tokens. The MH2 should be renamed with a space afterwards, as the other token in question - the correct one - is the very next on the list, alphabetically.

Thanks for your time.

**Comment by tooomm** [comment]
>Thanks for your time.

Thanks for your report!
