### ISSUE TITLE
Kiora, the Crashing Wave token issue

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Magic-Token#11]
Originally reported by @KarasuGamma in https://github.com/Cockatrice/Cockatrice/issues/2026:

> Currently, the Kraken token Kiora's emblem creates is tied to Kiora rather than the emblem. This is moderately inconvenient in situations where Kiora isn't in play and you don't have another Kraken to clone. Can this be reassigned to the emblem?

**Comment by Daenyth** [comment]
We can probably make it reverse-related to both the emblem and the card
