### ISSUE TITLE
Crimson Vow CR changes the names of most tokens in the game.

### ISSUE THREAD

**Issue by mainman879** [Cockatrice/Magic-Token#126]
The article detailing the changes is [here](https://magic.wizards.com/en/articles/archive/news/comprehensive-rules-changes-2021-11-10). In short, all generic tokens (Blood, Human Soldier, Thopter, etc) will now have the word Token added to their name. So instead of Blood it is now Blood Token, Human Soldier Token, Thopter token, etc. Any tokens that are created with a specific name (like [Jiang Yanggu creating Mowu](https://scryfall.com/card/gs1/22/jiang-yanggu)) are unaffected.

**Comment by Psithief** [comment]
Cringe.
