### ISSUE TITLE
Tokens.xml fails to validate

### ISSUE THREAD

**Issue by SlightlyCircuitous** [Cockatrice/Magic-Token#202]
When running `xmllint --schema ./cards.xsd ./tokens.xml` using the current v4 cards.xsd, I receive the following error:

`./tokens.xml:7: element cockatrice_carddatabase: Schemas validity error : Element 'cockatrice_carddatabase', attribute '{https://www.w3.org/2001/XMLSchema-instance}noNamespaceSchemaLocation': The attribute '{https://www.w3.org/2001/XMLSchema-instance}noNamespaceSchemaLocation' is not allowed.`

Am i doing something wrong or is this an issue of expectations mismatch between cards.xsd and tokens.xml?

I have been simply ignoring this message because I know the xml works fine with that attribute, but it would be nice if the validation tool would tell me everything is OK when I run it with a valid file.

**Comment by tooomm** [comment]
Try changing `https` to `http` in the w3.org URL.

Please also see #65 and especially #93, maybe there are also other linked issues.
Also https://github.com/Cockatrice/Cockatrice/pull/3710.

Psithief had concerns there as it looks like the XSD at Cockatrice is not perfect and would need an update to XSD v1.1.
Maybe you've some more insights there? Or the situation changed?

**Comment by SlightlyCircuitous** [comment]
That does actually fix the problem. Now that I look at it, both cards.xml and cards.xsd use `http` and only tokens.xml uses `https` so I guess it's just the odd one out for some reason. Should we change that in tokens.xml or is it like that for a reason?

**Comment by ebbit1q** [comment]
looking at the history this was introduced in #71

**Comment by ebbit1q** [comment]
looking at the latest spec it is required to be http, and xmllint is correct in refusing the https url https://www.w3.org/TR/xmlschema11-1/#sec-nss-special

**Comment by tooomm** [comment]
The URL is fixed since 2 years in #93 (https://github.com/Cockatrice/Magic-Token/pull/93/commits/c73fcaf43d8c309415f794f39ce9d633b0111258), that's why I knew http fixes it. :)

**Comment by ebbit1q** [comment]
when will #93 be ready for review though?

**Comment by tooomm** [comment]
I stopped working on it a long time ago, and just updated it from time to time as I like to see such a check at one point. Once #208 is merged, I would update it again.
Even as is, it allowed me to spot and fix many issues in the files already and helps to provide a good quality.

Though, the blocker for merging was, that Psithief had concerns and it looked like the XSD at Cockatrice is not perfect and would need an update to XSD v1.1 in order to make the check really be useful?
Please feel free to double check, I've no experience with XSD files and XML validation really. Maybe the situation changed or the concerns are not valid (any longer)! --> https://github.com/Cockatrice/Magic-Token/pull/93#issuecomment-711117488

**Comment by SlightlyCircuitous** [comment]
My understanding of Psithief's reasoning is that using XSD 1.0 and formatting the XMLs like we do necessitates that the schema expects elements to be in a certain order and so xmllint will throw an error if they aren't. Since Cockatrice doesn't really care about the order of elements, this could generate false positives and call valid-for-Cockatrice files 'invalid'. 

But, that seems like it would be a pretty rare false positive as we basically always put elements in the same order nowadays. cards.xml is generated automatically (right?), my updates to tokens.xml are generated near enough to automatically (and it seems like other people copy and paste the blank template if they do it manually so order is still preserved), and the challenge tokens will probably never be updated again (besides the proposition to swap them to v4, which was also done automatically).

It sounds like it would definitely be advantageous to switch to XSD 1.1, but it doesn't seem like not being able to make that switch should block automatic XML validation. Though maybe I am missing some other issues with XSD 1.0 since I am pretty new to this project.
