### ISSUE TITLE
Kibo's Bananas

### ISSUE THREAD

**Issue by Mortymacabre** [Cockatrice/Magic-Token#214]
is there any way to add an art for banana tokens i understand  wizards never made one but people dont read often enough that its becoming an issue playing he deck 
![29125](https://user-images.githubusercontent.com/129471040/229002883-1bc48afd-71ec-4b0f-8ea6-cf72972c0c53.jpg)

**Comment by ebbit1q** [comment]
the artist of this isn't properly credited, using google lens I found it is made by jackson moyer: https://www.artstation.com/artwork/NGaXEd

if you were to add their name to the bottom of your card we can include the url to it in the xml here: https://github.com/Cockatrice/Magic-Token/blob/6e1ce596bb498a7aecd1b49f544cf0045acb293f/tokens.xml#L507

**Comment by SlightlyCircuitous** [comment]
Can we assume fair use with attribution here? I didn't see anything about license either way on that site.

**Comment by SlightlyCircuitous** [comment]
I had a go at a token using mtgdesign to get a token frame. Please let me know if it's sufficient.

**Comment by ebbit1q** [comment]
fair use with attribution is generally accepted yeah, if the author were to say we've misappropriated their art we'd remove it of course.

**Comment by SlightlyCircuitous** [comment]
fair enough.
