### ISSUE TITLE
Lord of the Rings: Tales of Middle Earth Tokens

### ISSUE THREAD

**Issue by Keither85247** [Cockatrice/Magic-Token#226]
Hey,

I am dying to play this set with my friends. Will anyone take the time to upload the tokens and relate them to the cards? Thank you very much.

**Comment by ebbit1q** [comment]
We rely on volunteers to contribute them, you too can be a contributor. You can edit the tokens.xml in a text editor and upload them in a pull request, you can take a look at other prs as an example. eg https://github.com/Cockatrice/Magic-Token/pull/223/files

**Comment by ebbit1q** [comment]
We have a complete reference for the properties of the xml here https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#to-add-your-own-custom-cards-follow-these-steps

We don't have like a guide on how to specifically contribute to the tokens.xml, it comes down to adding `<reverse-related>` tags to tokens that are already in the list and adding new `<card>` entries with the right properties when a token is unique. Also you can add art (scryfall scans are preferred) with the `<set>` tags.

After editing you can use an xml validator to check if your file is correctly formatted (no missing closing tags etc). Then you can create a pr on github: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

If you'd like to ask some questions directly you can visit the #dev channel on our discord: https://cockatrice.us/discord

**Comment by SlightlyCircuitous** [comment]
I could write up the process I follow/notes I have into a guide if there is interest in that sort of thing.

**Comment by Keither85247** [comment]
That would be great. I would definitely find that beneficial. Thank you!

From: SlightlyCircuitous ***@***.***>
Date: Thursday, June 15, 2023 at 6:29 PM
To: Cockatrice/Magic-Token ***@***.***>
Cc: Keither85247 ***@***.***>, Author ***@***.***>
Subject: Re: [Cockatrice/Magic-Token] Lord of the Rings: Tales of Middle Earth Tokens (Issue #226)

I could write up the process I follow/notes I have into a guide if there is interest in that sort of thing.

**Comment by SlightlyCircuitous** [comment]
I wrote up an [article on editing the tokens file]( https://github.com/Cockatrice/Cockatrice/wiki/Tips-for-Contributing-to-the-Cockatrice-Tokens-File). It's designed to be relatively comprehensive so don't be intimidated by the length; I just wanted to make sure I answered questions that I thought might come up. If you have questions, feel free to @ me in #dev the discord

**Comment by ebbit1q** [comment]
you can now run oracle to get the new tokens

**Comment by Keither85247** [comment]
I super appreciate this!!! Thank you very much for letting me know

From: ebbit1q ***@***.***>
Date: Monday, June 19, 2023 at 11:58 AM
To: Cockatrice/Magic-Token ***@***.***>
Cc: Keither85247 ***@***.***>, Author ***@***.***>
Subject: Re: [Cockatrice/Magic-Token] Lord of the Rings: Tales of Middle Earth Tokens (Issue #226)

you can now run oracle to get the new tokens

**Comment by ebbit1q** [comment]
you're welcome

**Comment by tooomm** [comment]
> I wrote up an [article on editing the tokens file](https://github.com/Cockatrice/Cockatrice/wiki/Contributing-to-the-Cockatrice-Tokens-File). It's designed to be relatively comprehensive so don't be intimidated by the length; I just wanted to make sure I answered questions that I thought might come up. If you have questions, feel free to @ me in #dev the discord

That writeup is very comprehensive! Awesome, thanks a lot :)

I also linked it in the wiki here: https://github.com/Cockatrice/Magic-Token/wiki#contributing
