### ISSUE TITLE
Misplaced tokens

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Magic-Token#247]
1. Kadena's Silencer doesn't have the morph token associated with it.
2. The 1/1 Myr Token uses the 2/1 Myr Token art (from Brudiclad).

**Comment by ebbit1q** [comment]
I made a pr for your first point, I can't reproduce your second one, try deleting your image cache to redownload it

**Comment by JineteDV** [comment]
> I made a pr for your first point, I can't reproduce your second one, try deleting your image cache to redownload it

Done that multiple times already. After going through multiple sets, it seems like the issue is the 2XM and BBD's 1/1 Myr Token arts. BRC seems to be the newest set with the correct token art.

**Comment by tooomm** [comment]
@JineteDV Our data is correct:
https://github.com/Cockatrice/Magic-Token/blob/master/tokens.xml#L7195

You can check the picture links, they are fine. Also the ones from the sets Brudiclad is in.

Please check your local picture storage Cockatrice is using (`downloadedPics` folder), that should be cleared with the options to delete downloaded pictures in settings (that's what ebbit is referring to).
Or maybe you have some custom image in place?
