### ISSUE TITLE
Misplaced Tokens and For Mirrodin! auto attach

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Magic-Token#266]
1. For Mirrodin! doesn't auto attach like Living Weapon does.
2. Need Poison Counter token on Fynn, the Fangbearer, Phyresis Outbreak, Norn's Decree, Ajani, Sleeper Agent Emblem
3. Need Foretell token on KHC, WHO cards with Foretell and Edgin, Larcnous Lutenist
4. The only stickers that need tokens associated with them that actually had them were the 2 that produced tickets. None of the rest did.

**Comment by SlightlyCircuitous** [comment]
Thanks for reporting all of these! I have created a pull request that should fix all of these issues.
