### ISSUE TITLE
Modern Masters 3 has a 5/5 Dragon token erroneously associated to it; it should be a 4/4 Dragon token

### ISSUE THREAD

**Issue by ShrewMaster** [Cockatrice/Magic-Token#30]
I would change this myself, but I don't know which file I am allowed to edit, so I'm leaving this issue here.

**Comment by tooomm** [comment]
Can you be more clear?

Which MM3 card is mistakenly associated with a wrong dragon?

You can edit the tokens.xml file for your own for sure. Simple changes are pretty easy right in the browser, just hit the edit symbol (little pencil icon). Once you are done, you have to create a pull request. We then need to approve the changes first until they get merged into the file for everybody to use, so we double check. 👍

**Comment by ShrewMaster** [comment]
Ok, good to know :)

I did the changes in my own tokens.xml file and it worked perfectly, since it's an easy fix. Basically this happened last night when playing a game of Commander. My Dragonmaster Outcast made a 5/5 dragon token, but the image showed a 4/4 dragon token from MM3. I found that weird, so I investigated the card database. It turns out that the tokens file has a 5/5 dragon token associated with MM3, which is incorrect. You can confirm it here: http://magic.wizards.com/en/articles/archive/daily-magic-update/update-2017-03-07. The MM3 set has a 4/4 dragon token associated, produced by Broodmate Dragon, and not a 5/5 dragon token.

**Comment by Psithief** [comment]
This was fixed two days ago. #28

**Comment by tooomm** [comment]
@ShrewMaster yes, @Psithief is right.
This got fixed by another friendly user who handed in that change more quickly. ;)

You just need to update your local token database with Oracle to fetch the newest version.
Once we merge such changes in they are immediately available to everyone.

**Comment by ShrewMaster** [comment]
Indeed, I noticed this when trying to edit the token file, and found everything A-OK. Then Psithief came to confirm this. Apologies for any inconvenience caused!

**Comment by tooomm** [comment]
No worries. Thanks for reporting in the first place.
