### ISSUE TITLE
[Question] Source of inconsistent use of " (token)"?

### ISSUE THREAD

**Issue by erikfox** [Cockatrice/Magic-Token#40]
Seen here: https://github.com/Cockatrice/Magic-Token/blob/master/tokens.xml#L24

I'm wondering why the XML contains such inconsistent use of ` (token)` and ` (emblem)` in `<name>` tags?

[Based on the wiki](https://github.com/Cockatrice/Magic-Token/wiki/Token-updating-process-flow#first-pass-before-mtgjson-updates) my assumption is that this occurs during manual addition of entries to XML?

I bring this up because every time I've seen a compilation for card images, the naming never uses `(token)` or `(emblem)`, and instead delineates based on `/Tokens` directory.

**Comment by Psithief** [comment]
Object names must be unique. Therefore, there must be a way to distinguish them. Cockatrice does not have an "internal  directory structure", so this is unavoidable.

You don't want to add the token version of cards with `Embalm` or `Eternalize` to your deck editor by accident, do you?

**Comment by erikfox** [comment]
@Psithief I understand the need to distinguish original cards vs their respective tokens, what I don't understand is why some token entries have `(token)` and [others don't](https://github.com/Cockatrice/Magic-Token/blob/master/tokens.xml#L131).

e.g.
```xml
<card>
    <name>Adorned Pouncer (token)</name>
    <set picURL="http://media.wizards.com/2017/hou/en_mq4ItEvq7h.png">HOU</set>
    <color>B</color>
    <cmc>0</cmc>
    <type>Token Creature — Zombie Cat</type>
    <pt>4/4</pt>
    <tablerow>2</tablerow>
    <text>Double strike</text>
    <token>1</token>
    <reverse-related>Adorned Pouncer</reverse-related>
</card>
```
vs
```xml
<card>
    <name>Angel </name>
    <set picURL="http://cdn.staticneo.com/w/mtg/b/bb/Angel3.jpg">APC</set>
    <color>B</color>
    <cmc>0</cmc>
    <type>Token Creature — Angel</type>
    <pt>3/3</pt>
    <tablerow>2</tablerow>
    <text>Flying</text>
    <token>1</token>
    <reverse-related>Haunted Angel</reverse-related>
</card>
```

Would it be worth standardizing the use of `(token)` for all tokens? And if so, would that be something I could contribute?

**Comment by ZeldaZach** [comment]
The phrase `(token)` is used _if_ the token has the same name as a _real_ card. Since Angel has always been just a token, it's implied. However, Adorned Pouncer is a real card and it's token is not, so we need to distinguish it

**Comment by erikfox** [comment]
@ZeldaZach By 'we' do you mean the maintainers of this repo? Or is the convention inherited from some source like mtgjson.com?

I'm just curious about the naming patterns and where/how they occur. Not questioning whether or not there's logic behind them.

**Comment by ZeldaZach** [comment]
The token repo is maintained by the Cockatrice Project, sourced _by_ MTGJSON. We came up with the design for that

**Comment by Psithief** [comment]
@erikfox I see. I didn't realise you were not asking solely in the context of Cockatrice.

This repository is solely to serve Cockatrice and its idiosyncrasies. 
The primary method of selecting a card to include in a deck by is typing or partially typing its name, so players trying to select cards that have token versions need to be able to avoid choosing the token version at a glance.

![image](https://user-images.githubusercontent.com/1124846/28050243-04364be2-662f-11e7-9b25-723130005ce4.png)

> Would it be worth standardizing the use of `(token)` for all tokens? And if so, would that be something I could contribute?

I don't think players like seeing the `(token)`, as it would also appear in gameplay. I'm sure they would prefer the `Angel` image to be labelled as an `Angel` object, and so on. And changing that would be a simple find/replace operation using regular expressions, but thankyou for offering.
