### ISSUE TITLE
Incorrect C17 images for Cat Dragon, Rat, and Eldrazi Spawn

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Magic-Token#41]
The images for the "Rat " and Eldrazi Spawn tokens from C17 both use the image for "Gold".
Cat Dragon uses the image for Cat.

**Comment by Psithief** [comment]
my copy paste failed. I usually check before I upload. I'll know not to skip that.

**Comment by Thunderbeliever** [comment]
closed..so is it fixed?

**Comment by Psithief** [comment]
Yes, but I can't undo the damage done.
Everyone has to actually delete the C17 tokens with the wrong images from their filesystem.

**Comment by Thunderbeliever** [comment]
could you explain how to do so?

**Comment by Psithief** [comment]
Well, my understanding is that if you open Cockatrice and use the Card Database > Open custom image folder it will open a file window to a directory named "CUSTOM". 
Then you need to go up one directory and into downloadedPics / C17.
And then delete `Cat Dragon.png`, `Rat .png` and `Eldrazi Spawn.png`.

Restart the Cockatrice application and it will download the correct files.

**Comment by Thunderbeliever** [comment]
i have a Custom image folder but for some reason when i tell it to open via
cockatrice it does not go there.

**Comment by Thunderbeliever** [comment]
ok i think i got it thx i am doing as you said

**Comment by Psithief** [comment]
Tell your friends. :+1:
