### ISSUE TITLE
Find image for Archenemy: Nicol Bolas 3/3 black Horror token.

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Magic-Token#44]
I can't find a good source.

**Comment by tooomm** [comment]
It's not this one? https://magiccards.info/extra/token/archenemy-nicol-bolas/horror.html

**Comment by Psithief** [comment]
Haha, in fact, it is. It's merely that magiccards.info had been years out of date for so long that I stopped checking it. Thanks.

**Comment by tooomm** [comment]
Your welcome. The quality looks nice too! 👍

**Comment by Psithief** [comment]
https://magiccards.info/extra/token/commander-2017/dragon-1.html
https://magiccards.info/extra/token/commander-2017/dragon-2.html

Hmm. Just when you thought it was safe to scrape a website.

**Comment by tooomm** [comment]
Not just wizards gives us the run-around :)

Quality on mci not that bad after all? ;)
Saw you updated/switched a bunch to use mci over wizards: https://github.com/Cockatrice/Magic-Token/commit/14a45756678a83514150595fc39d9467c79b8f75

You have to consider that what we get from wizards is way smaller at first. If you look at it at the same size you get this:
![wizards-mci1](https://user-images.githubusercontent.com/9874850/30694307-b5faed56-9ed3-11e7-9c82-eae4f515fe3e.png)
A comparison of the same token next to each other is even worse...
![wizards-mci2](https://user-images.githubusercontent.com/9874850/30694311-b75425d2-9ed3-11e7-8c38-cff5d0afdfc2.png)

Direct wizards links might be more reliable and stable on the other hand.

We have no fallback or backup link to wizards included.
Which makes me think what would happen if we have two links for each in the scheme like this?
```
link1 mci         set1
link1 wizards     set1
link2 mci         set2
link2 wizards     set2
```
Will Cockatrice try the second link for a given set, or even just the next one on fail?
Aka do we iterate through all links for a card until one is working?
Or just newest/on top? Or just the link for a particular set?

Would look like this for 3/3 Hippo from AKH:
```
<card>
            <name>Hippo </name>
            <set picURL="https://magiccards.info/extras/token/amonkhet/hippo.jpg">AKH</set>
            <set picURL="https://media.wizards.com/2017/dw466ytu5_akh/en_WH5A9ESPOc.png">AKH</set>
            <color>G</color>
            <cmc>0</cmc>
            <type>Token Creature — Hippo</type>
            <pt>3/3</pt>
            <tablerow>2</tablerow>
            <token>1</token>
            <reverse-related>Mouth // Feed</reverse-related>
</card>
```

**Comment by Psithief** [comment]
@tooomm Maybe it's time to try it. Same set, two entries, first one a bad URL. I'll see what happens.

**Comment by Psithief** [comment]
@tooomm Ok, the behaviour is as follows:
As the XML file is read, there is one entry per card, per set. If there are multiple copies of the element (even if they have different URLs), only the last one will be saved to the map.
If that's not a valid URL, Cockatrice will try the next set in the list as a fallback, and continue until it runs out of fallbacks.
So we can't put multiple entries in `tokens.xml` to enable "fallback functionality" for URLs. Only the last URL will be in memory after XML parsing.
