### ISSUE TITLE
Challenge "token" broken

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Token#47]
See report: https://www.reddit.com/r/Cockatrice/comments/7bbrhk/i_noticed_that_the_challenge_deck_cards_were/

**Comment by Psithief** [comment]
@ZeldaZach Do you know what this is about?

**Comment by ZeldaZach** [comment]
No idea why it's "broken," but i'll look into it at some point this week

**Comment by ctrlaltca** [comment]
Looks like image links in https://github.com/Cockatrice/Magic-Token/blob/master/challenge_tokens.xml are broken, eg:
```
http://deckmaster.info/images/cards/-66612-hr.jpg
```
should be
https://deckmaster.info/images/cards/THS/-66612-hr.jpg

**Comment by Psithief** [comment]
You beat me to it. :) :+1:

**Comment by ZeldaZach** [comment]
So they added /SET_CODE/ to the URL. Gotcha. I can work up a fix later.

**Comment by Psithief** [comment]
Too late, already did. @ZeldaZach  :+1: 

Still, these should be three separate sets in the file. What were the names of the other two?
