### ISSUE TITLE
Upvote for silver-border sets.

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Magic-Token#48]
I'm not interested in doing tokens for silver-bordered sets. 

Do a thumbs-up reaction to this post to show demand for this.

**Comment by tooomm** [comment]
Did the former UN-sets have tokens, too?

Do you add the other (normal) tokens `UST` includes?
They have damn sweet full art token for angel, spirit, zombie and other common stuff.
https://magic.wizards.com/en/articles/archive/news/tokens-unstable-2017-11-21

**Comment by Thunderbeliever** [comment]
Thumbs down

**Comment by Psithief** [comment]
> Did the former UN-sets have tokens, too?

Former `Un-` sets went without errata for so long that they were too hard to work with.

> Do you add the other (normal) tokens UST includes?

Yes, but perhaps as part of the Rivals of Ixalan update.
