### ISSUE TITLE
1/1 Wolf (G) token art unavailable

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Token#49]
https://github.com/Cockatrice/Magic-Token/blob/master/tokens.xml#L4854

Related card which creates the token is this one: https://scryfall.com/card/csp/123

**Comment by Psithief** [comment]
Thanks for bringing this up.

**Comment by tooomm** [comment]
I would have offered a fix too, but had no idea how the token looked like.
Actually, even searching for it didn't let me find any... :D

Quick fix as always! Thanks 👍
