### ISSUE TITLE
another photobucket link broken

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Token#50]
Just like https://github.com/Cockatrice/Magic-Token/issues/49, same problem with:
https://github.com/Cockatrice/Magic-Token/blob/master/tokens.xml#L1105

I double checked all photobucket links because of https://github.com/Cockatrice/Cockatrice/issues/2955.

**Comment by Psithief** [comment]
Really, all the photobucket links need to be replaced.

**Comment by tooomm** [comment]
Just the two reported ones are broken for me right now by the way @Psithief. 👍 
All other links do work.

But to avoid further problems, exchanging all links sounds reasonable!
