### ISSUE TITLE
Reminder: Delete "(Unknown card name - token)"

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Token#52]
The latest, get rid of that when HOU rotates out of standard as stated in the code comment.

https://whatsinstandard.com/

**Comment by Psithief** [comment]
This issue is a whole year early.

**Comment by tooomm** [comment]
I'm sure I forgot about it in less time. ;P

Well, most likely the `(Unknown card name - token)` entry in the card and token list annoys me earlier...

**Comment by Psithief** [comment]
Only 19 more days.
