### ISSUE TITLE
Commander 2017 6/6 Dragon and 4/4 Dragon token pictures reversed

### ISSUE THREAD

**Issue by darklight0tr** [Cockatrice/Magic-Token#54]
4/4 Dragon should be: https://magiccards.info/extras/token/commander-2017/dragon-1.jpg
6/6 Dragon should be: https://magiccards.info/extras/token/commander-2017/dragon-2.jpg

Thanks!

**Comment by Psithief** [comment]
Wait what? I thought this got fixed already. Hmm

**Comment by Psithief** [comment]
Fixed!
Thank you for your contribution.

**Comment by Psithief** [comment]
Aha! https://github.com/Cockatrice/Magic-Token/issues/44#issuecomment-331125180

I made that comment because the files were swapped on magiccards.info. Now they're fixed, so my copy was out of date.

> https://magiccards.info/extra/token/commander-2017/dragon-1.html
> https://magiccards.info/extra/token/commander-2017/dragon-2.html
>
> Hmm. Just when you thought it was safe to scrape a website.

Thanks for bringing this to my attention, @darklight0tr

**Comment by darklight0tr** [comment]
Of course! It sucks when I third party causes an issue for you. Lol
Thanks for the quick fix!

-Tyler 
 
  On Fri, Mar 2, 2018 at 11:03 PM, Psithief<notifications@github.com> wrote:   
Aha! #44 (comment)

I made that comment because the files were swapped on magiccards.info. Now they're fixed, so my copy was out of date.


https://magiccards.info/extra/token/commander-2017/dragon-1.html
https://magiccards.info/extra/token/commander-2017/dragon-2.html

Hmm. Just when you thought it was safe to scrape a website.


Thanks for bringing this to my attention, @darklight0tr
