### ISSUE TITLE
scryfall took over mci

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Token#56]
Currently, that results in our mci token links for pictures do no work.
They correctly redirect other cards already.

Announcement: https://scryfall.com/blog/scryfall-magiccards-info-190

**Comment by Psithief** [comment]
Ok.
I don't have the time to fix this just now.

**Comment by Psithief** [comment]
So these sets are broken?

1. pPRE
2. pFNM

**Comment by Psithief** [comment]
Fixed in a13e622a339025cc2b6a05fa9d233c025703b444
