### ISSUE TITLE
Add a last-update field on the XML files

### ISSUE THREAD

**Issue by lsmoura** [Cockatrice/Magic-Token#6]
Is it feasible to add such information? When an app fetches information from you, it knows if their database needs updating or not.

**Comment by ctrlaltca** [comment]
That's a good idea, even if people would have to download the file anyway to get that information.
I see you are the new maintainer for mtgjson; we created this token repository (currently maintained by @Psithief ) because mtgjson doesn't contain all the tokens info.
Maybe you're planning to add token info to mtgjson?

**Comment by lsmoura** [comment]
Yes I am. I'm still getting around to fix somethings and I'm currently creating the color identity field for commander decks.

Next up will be tokens, probably. MTGJson caches all its files, but I'm planning on making a separate routine for tokens and a last update field would be useful to avoid recalculations.

**Comment by Psithief** [comment]
That would mean the general Cockatrice XSD would need to have the attribute, where it doesn't serve any purpose.

What if it's a separate file?

**Comment by Psithief** [comment]
> Next up will be tokens, probably. MTGJson caches all its files, but I'm planning on making a separate routine for tokens and a last update field would be useful to avoid recalculations.

Hmm, I would have expected you'd want artist names and set numbers and tokens that have multiple versions in the same set. I can't provide these in the Cockatrice database format .

**Comment by ctrlaltca** [comment]
Yep, maybe it would be better if we just drop this repo and concentrate the work directly inside mtgjson?

**Comment by tooomm** [comment]
> That's a good idea, even if people would have to download the file anyway to get that information.

@ctrlaltca Would it be possible, that Oracle checks the last-updated field (if we write it to our file) vs http://mtgjson.com/atom.xml (it has links to the changelog with version numbers and date) before downloading the file?
Or we just write the version number of the mtgjson source instead to check directly versus the feed. We could just save both information as well.


> What if it's a separate file?

@Psithief You mean like `tokens.json`?

**Comment by ctrlaltca** [comment]
@tooomm i suppose checking against http://mtgjson.com/json/version.json would be easier; anyway, this is OT and probably belongs to https://github.com/Cockatrice/Cockatrice/issues/210

**Comment by Psithief** [comment]
> Yep, maybe it would be better if we just drop this repo and concentrate the work directly inside mtgjson?

Guys, forget it. This repository is about images, what @lsmoura needs is info about actually printed tokens.

**Comment by ZeldaZach** [comment]
So what to do with this ticket?

**Comment by Psithief** [comment]
Close it, I believe.
