### ISSUE TITLE
Update database version to v4

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Token#60]
Currently `cockatrice_carddatabase version="3"` is used.

There is a new v4 style introduced in Cockatrice which will probably be the only one supported at one point.

**Comment by Psithief** [comment]
This sounds like something to do on the next update.

**Comment by Psithief** [comment]
In progress.

**Comment by Psithief** [comment]
There's no guide for this conversion, and everything I've tried so far has failed.

https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets
Cockatrice/Cockatrice#3511

@tooomm

**Comment by ctrlaltca** [comment]
I've just updated the wiki page with the needed information about the v4 card database format, hope it will be helpful. Let me know if something needs further clarification.

**Comment by Psithief** [comment]
So it turns out I got the conversion right, but I had my shortcut pointing to an old install of 32-bit Cockatrice. Oops.

**Comment by Psithief** [comment]
Closed in 233a2befd06999b632d86d31056221a12aed54ec.
