### ISSUE TITLE
Scryfall picture URLs not working anymore

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Token#73]
Scryfall deprecated their old image URLs that we still use:
https://scryfall.com/blog/deprecation-notice-old-price-fields-and-old-image-urls-207

Examples from the xml:
- Etherium Cell
https://img.scryfall.com/cards/large/en/taer/3.jpg
- Tezzeret the Schemer (Emblem)
https://img.scryfall.com/cards/large/en/taer/4.jpg
- 9 variants of "Angel"
https://img.scryfall.com/cards/large/en/tori/1.jpg
https://img.scryfall.com/cards/large/en/tc14/1.jpg
https://img.scryfall.com/cards/large/en/tm14/2.jpg
https://img.scryfall.com/cards/large/en/tgtc/1.jpg
https://img.scryfall.com/cards/large/en/p04/2.jpg
https://img.scryfall.com/cards/large/en/tavr/1.jpg
https://img.scryfall.com/cards/large/en/tisd/1.jpg
https://img.scryfall.com/cards/large/en/tzen/1.jpg
https://img.scryfall.com/cards/large/en/tcon/1.jpg
- many more...

**Comment by Psithief** [comment]
Oh dear.

**Comment by Psithief** [comment]
I am hoping that the API is capable enough to retrieve tokens and emblems easily.

**Comment by tooomm** [comment]
Gave this a try and got around it quickly.

**Comment by ZeldaZach** [comment]
You can use an image redirect instead now. `https://api.scryfall.com/cards/{scryfallId}?format=image` from MTGJSON will load it correctly

**Comment by tooomm** [comment]
>You can use an image redirect instead now

That's what my PR is using.
As they advised in their blog announcement I changed the links to:
`https://api.scryfall.com/cards/{setcode}/{number}?format=image`

Your proposal still uses the api and users might get rate limited when downloading many pictures.
And having to wait for the image link and following a redirect is slower than direct links.

My idea was to replace
`https://api.scryfall.com/cards/thou/9?format=image`
(or your `https://api.scryfall.com/cards/289a9593-151e-47d0-b0de-5eb9f061515a?format=image`)
with the direct and robust image link that gets returned by both api calls:
`https://img.scryfall.com/cards/large/front/2/8/289a9593-151e-47d0-b0de-5eb9f061515a.jpg` (truncated by last, unneeded part)
But I'm not doing that manually. :)

On the other hand the api links might be more universal and flexible.
Do we have to be worried about api limits and speed? Or that there might be a propblem with following redirects in the app etc.?

**Comment by ZeldaZach** [comment]
I highly recommend NOT pre-processing links for them. The way the PR/my idea works are good. There is no rate limit for SF at the moment so I’m not worried.

**Comment by tooomm** [comment]
Ok.

If you think the api links with uuid are even better, that can be a second step and somebody need to write a script for updating them.

**Comment by Psithief** [comment]
> If you think the api links with uuid are even better, that can be a second step and somebody need to write a script for updating them.

That's the part I thought I'd have to do.
