### ISSUE TITLE
Use UUID for image links from the Scryfall API

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Token#75]
Opened a new, separate issue to keep track of this.

See https://github.com/Cockatrice/Magic-Token/issues/73#issuecomment-517505477 and following comments.

Ideal pattern for image links in the token file would be:
`https://api.scryfall.com/cards/{scryfallOracleId}?format=image`,
with [*scryfallOracleId*](https://mtgjson.com/files/all-cards/#scryfallOracleId) from MTGJSON, in [Scryfall's documentation](https://scryfall.com/docs/api/cards) for their API it's `id` if I got it right.

**Comment by Psithief** [comment]
There most certainly is rate-limiting on even these simple API redirects, so this is not the right approach.
I'm replacing all of the ScryFall links with the direct links.

**Comment by tooomm** [comment]
Yes, I like avoiding the API, too. Even though Zach said there is no rate limit.
I hope they stick with their pattern now :)

**Comment by ZeldaZach** [comment]
Even if there was a limit, nobody is viewing every token at once... I also still disagree with hard links as their images may change often in location (as they have stated...) not a fan at all here

**Comment by Psithief** [comment]
> This new URL is much more stable, it will not change if a card is renumbered or moved to a new set.

[This](https://scryfall.com/blog/deprecation-notice-old-price-fields-and-old-image-urls-207) says they _won't_ change.

**Comment by ZeldaZach** [comment]
🤷‍♂ Have some conflicting information then, but if the website says it's stable then good enough for me. If we have issues down the line we can re-address it
