### ISSUE TITLE
Include the maintype property

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Magic-Token#79]
Without this, tokens arent grouped by type in the deck editor

See https://github.com/Cockatrice/Cockatrice/issues/3835

**Comment by Psithief** [comment]
I guess I could write a regular expression to do this.

**Comment by Psithief** [comment]
@skwerlman Does this look right to you? b731a58

**Comment by Psithief** [comment]
Bleh, wrong version.

**Comment by Psithief** [comment]
ec97b86

**Comment by skwerlman** [comment]
seems correct, but im not sure how trice will handle `State`s like adventure (i cant test atm). as long as that works as expected it should be good
