### ISSUE TITLE
Add version information to permit automated update checking

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Magic-Token#83]
This issue is about adding the version informations to the tokens.xml file and to an external "version.txt" file.
The file could be edited manually or by some CI after a commit on master.
It should contain the same exact version string contained in the tokens.xml file to permit automatic checking of new available versions.
Please see https://github.com/Cockatrice/Magic-Token/pull/82 and https://github.com/Cockatrice/Cockatrice/pull/3934 for more info

**Comment by tooomm** [comment]
>The file could be edited manually or by some CI after a commit on master.

CI could also check if the version is changed/increased with each PR for example.

**Comment by Psithief** [comment]
Ooh, tricky. Adding CI to a repository is something I have no experience with.
How is it managed and where?
What will we have to do differently?
Can it be bypassed?
What languages can the build scripts be written in?
