### ISSUE TITLE
goblin goliath doesn't have a "create x 1/1 goblin tokens" option in its right click menu like most token creators do

### ISSUE THREAD

**Issue by cjh0bbes** [Cockatrice/Magic-Token#86]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

**Comment by ebbit1q** [comment]
This is a cockatrice issue not a token issue, the issue happens because goblin goliath's text doesn't mention the creation of X tokens but rather of "a number of 1/1 red Goblin creature tokens equal to the number of opponents you have".

**Comment by ebbit1q** [comment]
oh, that's not how that works....

**Comment by ebbit1q** [comment]
I err fixed it, thanks for the report.

**Comment by tooomm** [comment]
@cjh0bbes you have to **update the card database** (especially the tokens file in the process) with the Oracle tool.

Let us know if it works for you now!

**Comment by Psithief** [comment]
@ebbit1q @tooomm  That's not how we do things around here. You've found an entire set (Game Night) that hasn't been processed for tokens, but you've only fixed one entry.

**Comment by ebbit1q** [comment]
aww, but the ticket said just that, I did what the ticket said
