### ISSUE TITLE
Scryfall image link changes

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Token#92]
As announced in their blog: https://scryfall.com/blog/upcoming-api-changes-to-scryfall-image-uris-and-download-uris-221

>Starting in mid-August, Scryfall will be transitioning our image and data origins to new subdomains. Images and bulk data items will stop being hosted on `img.scryfall.com` and `archive.scryfall.com` and they will move to new federated hosts at `c1.scryfall.com`, `c2.scryfall.com`, `c3.scryfall.com`, and so on, with new file paths.
>
>**Why are you doing this?**
>
>Scryfall is transitioning to a new file hosting provider to improve our scalability and also save money.
>
>**Will this break my existing code?**
>
>Only if you’ve been naughty. We don’t recommend that you ever try to manually construct a link to a file on `img.scryfall.com` or `archive.scryfall.com`. Instead you should fetch card data using our API or bulk file offerings, those objects always include the correct and up-to-date URI to card images and downloadable files.
>(...)
>
>If you have already been using the API to retrieve image and file URIs, nothing should change for you.
>
>**What if I have cached the old links? Will you set up any redirects?**
>
>Yes, we will be creating redirects for `img.scryfall.com` and `archive.scryfall.com`, but you should not permanently rely on these redirects. They should be considered temporary band-aids until you are able to update anything affected by the domain changes.
>
>**Can I still hotlink to the new origins?**
>
>Yes.
>
>**Do the new origins have a rate limit?**
>
>No, only api.scryfall.com has a rate limit.

---

Other notes:
- Scryfall also has PNG and JPG pictures. We currently use both mixed across the file
See [`image_uris` for "Academic Probation"](https://api.scryfall.com/cards/search?q=Academic%20Probation) for example.
- There is always a number attached to each picture. Should we scrape that for a cleaner file?
https://c1.scryfall.com/file/scryfall-cards/large/front/0/5/05521edf-f47f-4e7a-aec5-cdc4ae7368c2.jpg?1624589179

<br>

List of all tokens available at scyrfall (per set): https://scryfall.com/sets?type=token

**Comment by Psithief** [comment]
Oh, fun. 👎

**Comment by tooomm** [comment]
@ebbit1q Is this something you can try to look into as well and find a nice automated solution maybe? 😉 

We could use API redirects, or go with the new file locations before they stop maintaining the old redirects.

**Comment by tooomm** [comment]
Looks like `img.scryfall` links are finally 404ing.

As spotted in https://github.com/Cockatrice/Magic-Token/pull/131, e.g:
> https://img.scryfall.com/cards/large/front/f/f/ff1df646-52f5-4292-9fd5-5b8393f63931.jpg (HTTP 301 => 404)

We rely on around 500 of them.
